"""
ContentBrief Schema
===================
The structured output of Agent 01 (Content Strategist).
Created in PostgreSQL; triggers Agent 02 (Blog Writer) via a Redis event.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, HttpUrl, field_validator

from .trend_data import TrendData


# ─────────────────────────────────────────────────────────────────────────────
# Enumerations
# ─────────────────────────────────────────────────────────────────────────────

class BriefStatus(str, Enum):
    """Lifecycle states of a ContentBrief."""
    PENDING   = "pending"     # Created, waiting for Agent 02
    IN_REVIEW = "in_review"   # Agent 02 is actively writing
    PUBLISHED = "published"   # Post is live
    REWRITE   = "rewrite"     # Agent 03 scored < 60 — sent back for revision
    ARCHIVED  = "archived"    # Expired or superseded


class ContentTone(str, Enum):
    EDUCATIONAL   = "educational"
    CONVERSATIONAL = "conversational"
    AUTHORITATIVE  = "authoritative"
    OPINION_PIECE  = "opinion_piece"
    HOW_TO        = "how_to"
    LISTICLE      = "listicle"
    CASE_STUDY    = "case_study"


class TargetAudience(str, Enum):
    DEVELOPERS      = "developers"
    BUSINESS_OWNERS = "business_owners"
    MARKETERS       = "marketers"
    GENERAL_PUBLIC  = "general_public"
    ENTERPRISE      = "enterprise"


# ─────────────────────────────────────────────────────────────────────────────
# Sub-models
# ─────────────────────────────────────────────────────────────────────────────

class OutlineSection(BaseModel):
    """A single section in the proposed article outline."""
    heading: str = Field(..., description="Proposed H2 or H3 heading text")
    key_points: list[str] = Field(
        default_factory=list,
        description="Bullet points Agent 02 must cover in this section"
    )
    suggested_word_count: int = Field(
        default=250,
        ge=50,
        le=800
    )


class SEODirectives(BaseModel):
    """SEO directives generated by Claude, consumed by Agent 02's SEO formatter."""
    focus_keyword: str = Field(
        ...,
        description="Primary target keyword (must appear in title, H1, first 100 words)"
    )
    secondary_keywords: list[str] = Field(
        default_factory=list,
        max_length=10
    )
    target_keyword_density_pct: float = Field(
        default=1.2,
        ge=0.5,
        le=2.0,
        description="Desired keyword density as a percentage of total word count"
    )
    meta_title: str = Field(
        ...,
        max_length=65,
        description="SEO-optimized <title> tag (≤ 65 chars)"
    )
    meta_description: str = Field(
        ...,
        max_length=160,
        description="Meta description (≤ 160 chars)"
    )
    slug: str = Field(
        ...,
        description="URL-safe slug for the blog post"
    )
    canonical_url: Optional[HttpUrl] = None


class InternalLinkSuggestion(BaseModel):
    """A recommended internal link to include in the body of the post."""
    anchor_text: str
    target_slug: str
    relevance_score: float = Field(..., ge=0.0, le=1.0)


# ─────────────────────────────────────────────────────────────────────────────
# Main Schema
# ─────────────────────────────────────────────────────────────────────────────

class ContentBrief(BaseModel):
    """
    Canonical ContentBrief — the primary artifact produced by Agent 01.

    Written to PostgreSQL (table: content_briefs) and referenced by Agent 02
    and Agent 03 throughout the content lifecycle.
    """

    # ── Identity ──────────────────────────────────────────────────────────
    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        description="Primary key — also used as trace ID across all three agents"
    )
    version: int = Field(
        default=1,
        ge=1,
        description="Incremented on each Agent 03-triggered rewrite"
    )
    parent_brief_id: Optional[uuid.UUID] = Field(
        None,
        description="Points to the previous version when this is a rewrite brief"
    )

    # ── Source trend ──────────────────────────────────────────────────────
    trend: TrendData = Field(
        ...,
        description="The TrendData record that inspired this brief"
    )

    # ── Content strategy ──────────────────────────────────────────────────
    title: str = Field(
        ...,
        min_length=10,
        max_length=120,
        description="Proposed article title (will become H1)"
    )
    tone: ContentTone = Field(default=ContentTone.EDUCATIONAL)
    target_audience: TargetAudience = Field(default=TargetAudience.DEVELOPERS)
    target_word_count: int = Field(
        default=2000,
        ge=1500,
        le=2500,
        description="Agent 02 must produce content within this range"
    )

    # ── Outline ───────────────────────────────────────────────────────────
    outline: list[OutlineSection] = Field(
        default_factory=list,
        description="Ordered list of sections Claude proposed for this post"
    )

    # ── SEO ───────────────────────────────────────────────────────────────
    seo: SEODirectives

    # ── Internal links ────────────────────────────────────────────────────
    internal_link_suggestions: list[InternalLinkSuggestion] = Field(
        default_factory=list,
        max_length=5
    )

    # ── Agent 02 execution hints ──────────────────────────────────────────
    priority: int = Field(
        default=5,
        ge=1,
        le=10,
        description="1 = lowest, 10 = highest. Rewrite briefs default to 8."
    )
    generate_featured_image: bool = Field(
        default=True,
        description="Whether Agent 02 should call DALL-E 3 + Cloudinary"
    )
    image_prompt_hint: Optional[str] = Field(
        None,
        description="Optional art-direction hint for DALL-E 3"
    )
    publish_targets: list[str] = Field(
        default_factory=lambda: ["wordpress"],
        description="CMS targets: 'wordpress', 'webflow', etc."
    )

    # ── Lifecycle ─────────────────────────────────────────────────────────
    status: BriefStatus = Field(default=BriefStatus.PENDING)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    assigned_to_agent: Optional[str] = Field(
        None,
        description="Worker ID of Agent 02 instance currently processing this brief"
    )

    # ── Agent 03 audit feedback ───────────────────────────────────────────
    last_audit_score: Optional[float] = Field(
        None,
        ge=0.0,
        le=100.0,
        description="Set by Agent 03; triggers rewrite if < 60"
    )
    rewrite_instructions: Optional[str] = Field(
        None,
        description="Agent 03's natural-language instructions for the rewrite"
    )

    @field_validator("updated_at", mode="before")
    @classmethod
    def set_updated_at(cls, v):
        return datetime.utcnow()

    def is_rewrite(self) -> bool:
        return self.parent_brief_id is not None

    def redis_payload(self) -> dict:
        """Minimal payload emitted via the 'content_briefs_ready' Redis event."""
        return {
            "brief_id": str(self.id),
            "title": self.title,
            "priority": self.priority,
            "version": self.version,
            "is_rewrite": self.is_rewrite(),
            "focus_keyword": self.seo.focus_keyword,
        }

    model_config = {"json_schema_extra": {"example": {
        "title": "How LLM Agents Are Transforming Production Software",
        "tone": "educational",
        "target_audience": "developers",
        "target_word_count": 2000,
        "priority": 7,
    }}}
